### ISSUE TITLE
 Inspiration engine 

### ISSUE THREAD

**Issue by Alchimista56** [daedalus4096/ThaumicWonders#49]
How should it works?
The explain is too poor, i've searched some guide on internet but seems like nobody talk about that.

**Comment by daedalus4096** [comment]
I'm sorry for the lack of clarity.  Like other research aids, the Inspiration Engine needs to be placed within four blocks of a research table, either on the same y-level or one above it.  If placed correctly, you'll see it show up as a selectable icon when you use the research table.  It then needs to be supplied with essentia in order to supply you with any bonus cards for the research minigame.  You'll know it's working if you draw a card titled "Induced Inspiration".  Is that more clear for you?  I'll try to update the Thaumonomicon entry with more information.

**Comment by daedalus4096** [comment]
The Thaumonomicon entry for the Inspiration Engine has been updated in 1.8.0.  Hopefully that makes things clearer.
